# extensions/shoppable-videos/shopify.extension.toml

api_version = "2024-01"

[[extensions]]
uid = "74af24ad-ce8d-4797-2594-486aec766f170499fadc"
type = "theme"
name = "Reels App Theme"
handle = "reels-app"

  [[extensions.blocks]]
  name = "Reels Carousel Widget"
  type = "reels-carousel"
  file = "blocks/reels-carousel.liquid"
  target = "section"

  [[extensions.blocks]]
  name = "Reels Story Widget"
  type = "reels-story"
  file = "blocks/reels-story.liquid"
  target = "section"